name: CI/CD Pipeline
on:
  push:
    branches:
      - main
  jobs:
    build-and-deploy:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Log in to Docker Hub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: Build and push backend
          run: |
            cd backend
            docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/my-chat-backend:latest 
            docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-chat-frontend:latest 

        - name: Build and push frontend
          run: |
            cd frontend/my-chat-app
            docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/my-chat-frontend:latest 
            docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-chat-frontend:latest
            